spring.application.name=EcoCiclo-API

spring.datasource.url=jdbc:postgresql://ecociclo_db_user:V4ByDQBUWrMP19NpPkbGZbUibeREQTnC@dpg-d8lc9kn7f7vs739855ng-a.oregon-postgres.render.com/ecociclo_db

spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

server.port=${PORT:8080}